import React from 'react';

const DocContainer: React.FC = () => {
    return (
        <div className="bg-white text-main-background w-full flex-1 overflow-y-auto p-5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id fringilla sapien, volutpat rhoncus ipsum. Duis malesuada vel tortor ac imperdiet. In arcu tellus, dapibus a tempor non, hendrerit ut massa. Sed rutrum porttitor velit, sed fringilla diam finibus ut. Nunc sit amet risus ac purus efficitur egestas. Suspendisse tincidunt ornare augue feugiat scelerisque. Nunc euismod leo ac ligula bibendum pharetra. Sed metus turpis, semper quis imperdiet vitae, fermentum sit amet ligula. Proin sit amet pellentesque dui, vitae hendrerit lectus. Aenean molestie sapien ante, sed congue ligula pretium ac.

            Fusce vitae fermentum diam. Morbi rutrum metus nec orci porta cursus. Morbi tristique eleifend lacus sed suscipit. Fusce nisl enim, accumsan euismod commodo id, mattis ac nulla. Sed nec venenatis purus. Nullam dictum neque massa, sed facilisis nibh consequat vitae. Donec lacus diam, tempor vitae eros sed, viverra pellentesque nisi. Quisque egestas, purus vitae tincidunt fermentum, ante nunc dictum sapien, nec rutrum dui turpis ut sapien. Maecenas aliquam nisl nec lorem tempor aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc id semper diam, sed finibus est. Nulla vestibulum sapien vel augue finibus posuere.

            Vivamus interdum consequat finibus. Suspendisse potenti. Nam in sapien rhoncus, fermentum urna vitae, placerat dui. Nullam aliquam vulputate turpis, eget aliquam ipsum cursus in. Proin dictum dui urna, vel volutpat sem consequat ut. Donec efficitur nisl eget accumsan semper. Pellentesque venenatis auctor diam nec convallis. Curabitur molestie gravida nulla vitae iaculis. Ut volutpat, neque quis venenatis dapibus, mi dolor fermentum erat, et laoreet velit dolor ut sapien. Integer bibendum sapien tortor, a eleifend purus fringilla sit amet. Mauris purus nisi, fermentum eu nulla auctor, facilisis pellentesque neque. Vivamus mattis, leo ut vestibulum semper, ipsum elit aliquam lacus, vitae porta massa lectus ac nunc. Vivamus tortor ligula, pellentesque sit amet tincidunt sed, vestibulum a ex.

            Nunc eget tempor tortor. Donec lacinia et augue tempor molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in ipsum scelerisque, tempor dolor in, consequat nulla. Aenean quis aliquam leo. Nam ut quam maximus, ultrices eros finibus, feugiat augue. Vestibulum tempus mi massa, et semper turpis malesuada vel. Vestibulum tortor est, finibus non arcu quis, interdum elementum metus. Nulla nec euismod ipsum. Mauris id eleifend mauris.

            Curabitur a suscipit nulla, et ullamcorper tortor. Aenean quis pharetra velit. Aenean sed tempus nulla. Morbi pharetra auctor mi, vitae volutpat dolor suscipit vel. Pellentesque nec aliquam enim. Nam ante nisl, eleifend et ultricies at, posuere ac felis. Vestibulum et dignissim dui, ut finibus ligula. Ut nec ante turpis. Integer id nulla velit. Etiam at mauris at lacus faucibus sollicitudin id ut diam. Nulla at sapien et mauris efficitur aliquam nec eu enim. Integer ultricies mi est, in mattis diam finibus ac. Mauris eget sem ac ipsum placerat porta at sit amet odio. Vivamus tempus quam massa, nec volutpat libero blandit quis. Cras sodales dui ex, ut laoreet nibh blandit sed. Donec vulputate nisi lectus, ut aliquet dui posuere non.

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id fringilla sapien, volutpat rhoncus ipsum. Duis malesuada vel tortor ac imperdiet. In arcu tellus, dapibus a tempor non, hendrerit ut massa. Sed rutrum porttitor velit, sed fringilla diam finibus ut. Nunc sit amet risus ac purus efficitur egestas. Suspendisse tincidunt ornare augue feugiat scelerisque. Nunc euismod leo ac ligula bibendum pharetra. Sed metus turpis, semper quis imperdiet vitae, fermentum sit amet ligula. Proin sit amet pellentesque dui, vitae hendrerit lectus. Aenean molestie sapien ante, sed congue ligula pretium ac.

            Fusce vitae fermentum diam. Morbi rutrum metus nec orci porta cursus. Morbi tristique eleifend lacus sed suscipit. Fusce nisl enim, accumsan euismod commodo id, mattis ac nulla. Sed nec venenatis purus. Nullam dictum neque massa, sed facilisis nibh consequat vitae. Donec lacus diam, tempor vitae eros sed, viverra pellentesque nisi. Quisque egestas, purus vitae tincidunt fermentum, ante nunc dictum sapien, nec rutrum dui turpis ut sapien. Maecenas aliquam nisl nec lorem tempor aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc id semper diam, sed finibus est. Nulla vestibulum sapien vel augue finibus posuere.

            Vivamus interdum consequat finibus. Suspendisse potenti. Nam in sapien rhoncus, fermentum urna vitae, placerat dui. Nullam aliquam vulputate turpis, eget aliquam ipsum cursus in. Proin dictum dui urna, vel volutpat sem consequat ut. Donec efficitur nisl eget accumsan semper. Pellentesque venenatis auctor diam nec convallis. Curabitur molestie gravida nulla vitae iaculis. Ut volutpat, neque quis venenatis dapibus, mi dolor fermentum erat, et laoreet velit dolor ut sapien. Integer bibendum sapien tortor, a eleifend purus fringilla sit amet. Mauris purus nisi, fermentum eu nulla auctor, facilisis pellentesque neque. Vivamus mattis, leo ut vestibulum semper, ipsum elit aliquam lacus, vitae porta massa lectus ac nunc. Vivamus tortor ligula, pellentesque sit amet tincidunt sed, vestibulum a ex.

            Nunc eget tempor tortor. Donec lacinia et augue tempor molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in ipsum scelerisque, tempor dolor in, consequat nulla. Aenean quis aliquam leo. Nam ut quam maximus, ultrices eros finibus, feugiat augue. Vestibulum tempus mi massa, et semper turpis malesuada vel. Vestibulum tortor est, finibus non arcu quis, interdum elementum metus. Nulla nec euismod ipsum. Mauris id eleifend mauris.

            Curabitur a suscipit nulla, et ullamcorper tortor. Aenean quis pharetra velit. Aenean sed tempus nulla. Morbi pharetra auctor mi, vitae volutpat dolor suscipit vel. Pellentesque nec aliquam enim. Nam ante nisl, eleifend et ultricies at, posuere ac felis. Vestibulum et dignissim dui, ut finibus ligula. Ut nec ante turpis. Integer id nulla velit. Etiam at mauris at lacus faucibus sollicitudin id ut diam. Nulla at sapien et mauris efficitur aliquam nec eu enim. Integer ultricies mi est, in mattis diam finibus ac. Mauris eget sem ac ipsum placerat porta at sit amet odio. Vivamus tempus quam massa, nec volutpat libero blandit quis. Cras sodales dui ex, ut laoreet nibh blandit sed. Donec vulputate nisi lectus, ut aliquet dui posuere non.
        </div>
    );
}

export default DocContainer;